package com.example.royalfreshapp.ui.screens

import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.royalfreshapp.R // Import R from your actual project package
import com.example.royalfreshapp.ui.theme.RoyalFreshTheme // Assuming Theme.kt exists
import kotlinx.coroutines.delay

@Composable
fun SplashScreen(onTimeout: () -> Unit) { // Changed parameter to lambda
    val alpha = remember { Animatable(0f) } // Start with transparent

    LaunchedEffect(key1 = true) {
        alpha.animateTo(
            targetValue = 1f,
            animationSpec = tween(durationMillis = 1500) // Fade in duration
        )
        delay(2000) // Hold splash screen for 2 seconds
        onTimeout() // Execute the provided lambda after delay
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.White), // You can change the background color
        contentAlignment = Alignment.Center
    ) {
        Image(
            // Use the actual R class generated by Android Studio
            painter = painterResource(id = R.drawable.logo),
            contentDescription = "Royal Fresh Logo", // English description
            modifier = Modifier
                .size(250.dp) // Adjust size as needed
                .alpha(alpha.value) // Apply fade-in animation
        )
    }
}

// --- Preview --- 
@Preview(showBackground = true)
@Composable
fun SplashScreenPreview() {
    RoyalFreshTheme {
        SplashScreen {} // Pass an empty lambda for preview
    }
}
